### ISSUE TITLE
Maybe don't ask the user to *describe* a chart

### ISSUE THREAD

**Issue by thany** [whoiskatrin/chart-gpt#11]
I thought since this is an AI tool, I can safely trust the I in AI 😀

![image](https://user-images.githubusercontent.com/152227/234044599-eee8043a-bd48-47a6-befb-a8d08e7ecfdf.png)

How wrong I was. This tool doesn't know what the other popular frameworks are, and thus makes no attempt to find them, and has no idea how or what to compare. It only incorrectly claims jQuery to offer more value 😂

In all seriousness, a description clearly isn't what's required. The "description" is more likely a well defined maths-like language, perhaps something akin to latex.

**Comment by KenzoBenzo** [comment]
Fixed in the latest release!
