### ISSUE TITLE
It doesn't work anymore

### ISSUE THREAD

**Issue by thany** [whoiskatrin/chart-gpt#18]
It seems to be(hopefully temporarily) kacked. So when I enter a prompt, I see the loading animation underneath it. After 2-3 seconds, the loading animation disappears and no graph is drawn - as if I hadn't pressed the Draw button yet.

I tried something seemingly simple and concise: `compare EUR against USD over the past 10 years` and even `please draw a line from the bottom left to the top right`. Especially the latter one should be lemon squeezy for an AI model.

**Comment by whoiskatrin** [comment]
WIP

**Comment by thany** [comment]
Of course it is. Just letting you know 🙂

**Comment by sampath88** [comment]
@thany i tried the same prompt, i got the output. i don't know the generated output is correct or not but it's generated something.


![Screenshot from 2023-05-03 16-56-43](https://user-images.githubusercontent.com/51907206/235904195-dd09e22c-b88b-481a-861f-61bc11f027d2.png)

**Comment by whoiskatrin** [comment]
fixed now
