### ISSUE TITLE
Suggestion: Add support for colors

### ISSUE THREAD

**Issue by sezze** [whoiskatrin/chart-gpt#20]
Hi, cool product!

I created this truly inspirational chart:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/9763776/234218726-2fb7f594-385a-4335-965b-98a46ae94554.png">

However if I change the prompt to
```
Show a pie chart of the most used hotdog toppings. Use colors that match the toppings.
```
I will get the same output, as it seems like custom colors are not supported, the received JSON data doesn't contain any additional information. Thought colors in general would be quite fun to have.

**Comment by whoiskatrin** [comment]
WIP

**Comment by whoiskatrin** [comment]
Done, a very kind contributor just added this. Thank you @hedwigz
