### ISSUE TITLE
Bug: x-axis label missing

### ISSUE THREAD

**Issue by laurenwalker** [whoiskatrin/chart-gpt#26]
<img width="647" alt="Screenshot 2023-04-25 at 4 03 38 PM" src="https://user-images.githubusercontent.com/6643222/234391028-26d8614d-fa84-45d9-bc90-ef5dfbbe79fe.png">

The first bar in the series is missing an x-axis label. On hover, the tooltip shows it is New York City.

**Comment by whoiskatrin** [comment]
It's on to-do list
