### ISSUE TITLE
Request: More accurate legends

### ISSUE THREAD

**Issue by laurenwalker** [whoiskatrin/chart-gpt#27]
I created a couple bar charts today and the legend defaults to "value". More accurately, the legend should show the name of the data type. In this example, the legend  should say "Shootings"

<img width="647" alt="Screenshot 2023-04-25 at 4 03 38 PM" src="https://user-images.githubusercontent.com/6643222/234391545-ca4edb44-422f-4f7f-b2b2-f836b4dd4583.png">

**Comment by whoiskatrin** [comment]
@laurenwalker WIP

**Comment by whoiskatrin** [comment]
Done
