### ISSUE TITLE
install error  when run yarn commond

### ISSUE THREAD

**Issue by x3hong** [whoiskatrin/chart-gpt#34]
**command:** 
yarn

**output :**

yarn install v1.22.10
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "=/@fortawesome%2ffontawesome-svg-core: Invalid URI \"=/@fortawesome%2ffontawesome-svg-core\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/didi/me/chart-gpt/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by PalAditya** [comment]
Did you try removing package-lock.json and rechecking, as suggested in the message? 🤔

**Comment by sampath88** [comment]
It worked fine for me, without removing package-lock.json file too.
yarn -v
1.22.5
