### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by ramnes** [whoiskatrin/chart-gpt#4]
Hey there,

I get a 500 on any request, on both domains (chartgpt.dev and chart-gpt-blush.vercel.app).

The API call that fails is POST /api/get-type.

**Comment by uttej-vsk** [comment]
![Screenshot 2023-04-24 at 2 44 43 PM](https://user-images.githubusercontent.com/83727090/233953328-f497b199-9363-4e0e-96bd-08cb9c3256a2.png)

Not only that, even after 500 error, we see a loading animation on the screen. It is supposed to stop.

**Comment by whoiskatrin** [comment]
fixed
