### ISSUE TITLE
Utilize code interpreter to take in datasets

### ISSUE THREAD

**Issue by merrillcook0** [whoiskatrin/chart-gpt#57]
I have not tried this out, but this is based on [this video](https://www.linkedin.com/posts/aigpt_ai-chatgpt-ugcPost-7061248553414766592-xSHS?utm_source=share&utm_medium=member_desktop) of the code interpreter plugin for chatGPT.

The idea here is that typing datasets into a chat prompt is tedious. Perhaps we should pass an uploaded data file to code interpreter and then specify a response format suitable for reCharts API.

**Comment by whoiskatrin** [comment]
This is not a publicly available plugin. Only for people on the list for now.
