### ISSUE TITLE
Allow formatting options via prompts 

### ISSUE THREAD

**Issue by christopherkindl** [whoiskatrin/chart-gpt#58]
Hi Kate,

awesome tool you created and thanks for using tremor for some charts. One suggestion that might be very helpful is to allow formatting via the prompt interface, e.g.:

"Show me an area chart with Running data for Monday - 10km, Tuesday - 20km, Wednesday - 12km, Thursday - 9km, Friday - 11km. Format data and y-axis with "km"-suffix."

**Comment by whoiskatrin** [comment]
added as a UI element
