### ISSUE TITLE
could not generate chart in localhost and isssue with yarn

### ISSUE THREAD

**Issue by samayp42** [whoiskatrin/chart-gpt#59]
the chart is not generating and also when I write command yarn install it gives output zsh:no command found.

**Comment by rupeshshandilya** [comment]
Make sure that yarn is Installed in your system

**Comment by rupeshshandilya** [comment]
> the chart is not generating and also when I write command yarn install it gives output zsh:no command found.

Make sure that yarn is Installed in your system
