### ISSUE TITLE
RoadmapGPT

### ISSUE THREAD

**Issue by mrna0** [whoiskatrin/chart-gpt#64]
Hello, I created a project on the fork of ChartGPT that can create roadmaps for any desired field. If you'd like, you can add this project as a branch to your main project. However, I couldn't find the steps to do this, so I think I need a roadmap too :)

https://github.com/mrna0/chart-gpt/tree/roadmap

**Comment by whoiskatrin** [comment]
This is amazing! Do you want to add a PR into this project and we can merge? Fab!
