### ISSUE TITLE
API Keys Issue

### ISSUE THREAD

**Issue by ritztechnologies** [whoiskatrin/chart-gpt#70]
After cloning this repository most of the apis are failing, do we need to add only Open AI key or all the keys mentioned in .env file?

**Comment by whoiskatrin** [comment]
Please, look at https://github.com/whoiskatrin/chart-gpt/blob/main/.env.example

**Comment by ritztechnologies** [comment]
Thanks for the quick response, that means all the keys including Bard.AI have to be updated in the .env file

**Comment by whoiskatrin** [comment]
​Correct. If you want to contribute, then once you open a PR, preview vercel env for PR will have all the keys, so you can test it.

**Comment by ritztechnologies** [comment]
Ok thank you!
