### ISSUE TITLE
Logging and API Key Leakage Concerns in OpenAI Project Submission

### ISSUE THREAD

**Issue by wertycn** [whoiskatrin/chart-gpt#72]
Thank you very much for the author's contribution. This is a great project! However, I have some questions. In this submission, the address for OpenAI API has been changed, and it seems that withlogging is used for logging. The default deployment of the project may pose risks of API key leaking. Would it be more reasonable to use other methods for logging?

commit: 
https://github.com/whoiskatrin/chart-gpt/commit/a86112d64c99db26a0f414db029e493bbf83bdff

**Comment by whoiskatrin** [comment]
I don't think it poses any risks of API key leaking. It's deployed on our private Vercel env, and all the secrets are hidden.
