### ISSUE TITLE
Error running locally

### ISSUE THREAD

**Issue by sudarshan-koirala** [whoiskatrin/chart-gpt#73]
Hi @whoiskatrin, Is it possible to use the app locally with just providing our openai api key only ?
I followed the instructions provided in the repo, but got the error which is attached as screenshot. Do we need to provide other variables other than openai api key in .env file ? 

Thank you for your contribution. I was planning to create a youtube video about this but got confused on how to use it locally. 
A better documentation would help users trying to use the app locally.

<img width="1349" alt="image" src="https://github.com/whoiskatrin/chart-gpt/assets/14214659/3dd64fa8-b076-4010-948a-ef539b864622">

**Comment by sudarshan-koirala** [comment]
A follow up question, do we still need to buy credits while we run the app locally ? It is still showing on the top right corner about logging in and the remaining credits. That's quite confusing or it can be just me who got confused 🤔

**Comment by memorx** [comment]
Hello, were you able to resolve this issue, I am facing the same issue right now.

**Comment by sudarshan-koirala** [comment]
@memorx Nope. I am waiting for the reply from @whoiskatrin or anyone else who has fixed/solved this.

**Comment by KenzoBenzo** [comment]
Hey @sudarshan-koirala & @memorx — apologies we've yet to update the readme! You'll want to supply the `BARD_KEY` since the app is now using the [PaLM API](https://developers.generativeai.google/products/palm?authuser=1)

**Comment by phongtnit** [comment]
> Hey @sudarshan-koirala & @memorx — apologies we've yet to update the readme! You'll want to supply the `BARD_KEY` since the app is now using the [PaLM API](https://developers.generativeai.google/products/palm?authuser=1) in order to provide sources!

Could I use Open API instead of PaLM API? Thanks for your help,

**Comment by whoiskatrin** [comment]
Hey, guys, to run locally, you'd need to use your own PaLM or OpenAI keys. I don't provide there. Read the instructions in the README how to setup these in the settings
