### ISSUE TITLE
Use of other LLMs other than Open API

### ISSUE THREAD

**Issue by junoriosity** [whoiskatrin/chart-gpt#74]
I really do like your package, great work. :)

However, I wonder whether it is possible to use other LLMs from Huggingface for accomplishing the same feat. :)

**Comment by brandonbiggs** [comment]
I'm also interested in using other LLMs. I haven't tested it yet, but it looks like we may be able to just change the URL specified here - https://github.com/whoiskatrin/chart-gpt/blob/afb3c7b8322f92941933a7cba2f5bca02121a738/pages/api/get-json.ts#L22 as long as the local LLM responds with the properly formatted json.

**Comment by Sammindinventory** [comment]
has anyone implemented it locally?

**Comment by whoiskatrin** [comment]
switched to PaLM, use BARD API key locally
